### ISSUE TITLE
VMware issues

### ISSUE THREAD

**Issue by Seelge** [Seelge/TrackballScroll#1]
Running the program in a WMware Windows host does not allow scrolling in a Linux guest operating system.

Note: The middle button down/up events do work.
###### Reproduce
- run the program
- hover a WMware window with a Linux guest
- press an X-Button and move the trackball
###### Result
- the cursor moves
- no wheel events are transmitted to the guest operating system
###### Expected behavior
- the cursor does not move while the X-Button is pressed
- scrolling works

**Comment by leohinojosa** [comment]
This is not an issue for HyperV or VirtualBox, i have been running an ubuntu based image and it works as expected, 

could this be a specific VMWare Issue ?

**Comment by Seelge** [comment]
Closing enhancement: No known solution.

**Comment by Seelge** [comment]
As of 2018-01-21, scrolling works using VMware and Ubuntu.
