### ISSUE TITLE
The release build is x64 only

### ISSUE THREAD

**Issue by fijam** [Seelge/TrackballScroll#13]
This is a minor issue, but the binary included under releases won't work on 32-bit systems.

I know that the year is 2017 and all, but there are still cases (like thin clients with <4GB RAM) where 32-bit Windows systems continue to be used. 

I built it myself and it works, but having to download Visual Studio just to build a 170KB binary seems unnecessary.

**Comment by ArmanHayots** [comment]
You can build it using SharpDevelop (with MS Build Tools 2015 installed), it only needs a few modifications. 
Looks like author set x64 instead of AnyCPU in project options.

**Comment by Seelge** [comment]
Thanks for the issue report. Unfortunately I do not have the time to test and support 32 bit versions (which would be expected when releasing a 32 bit executable).

**Comment by ArmanHayots** [comment]
This caused by WinAPI, am I right?
I forgot about it. 
So that's why you set x64 only.

**Comment by Seelge** [comment]
I don't remember a specific reason but with hooks and native calls involved it was probably a "caution first" setting in order to avoid as much issues as possible.
