### ISSUE TITLE
Middle button click freeze after installing the Windows 10 Creators Update

### ISSUE THREAD

**Issue by Seelge** [Seelge/TrackballScroll#14]
It seems TrackballScroll has a problem with the Windows 10 Creators Update (April 2017). Middle button clicks seem to freeze mouse input by several seconds.

Any ideas what could cause this? A similar bug did exist in earlier, pure C++ versions, of this program, but it did only appear when metro style apps were running.

**Comment by ArmanHayots** [comment]
Look's like the only way to beat all sorts of troubles is writing a custom driver.
It's too bad that my skills are not enough for this.

**Comment by Seelge** [comment]
Some test results:
* sendinput is used to send mouse events, which works fine.
* The sentinput line which sends the middle button click causes the freeze/delay. Without it, everything works... without actually doing anything.
* Using [TestApi](http://testapi.codeplex.com/) to send the middle button mouse click causes the same issue.
* Using [TestApi](http://testapi.codeplex.com/) to send a mouse move causes the same issue.
* The delay/freeze time varies and by clicking wildly it is possible to create a zombie process which cannot be killed without restarting.

**Comment by Seelge** [comment]
Fixed by @johnwoolee 

Thanks for the PR!
