### ISSUE TITLE
Scroll behaves very strange on high speed.

### ISSUE THREAD

**Issue by saroff** [Seelge/TrackballScroll#17]
When i'm rolling ball really fast, then scroll becomes very slow and stepped.
Win 10, can reproduce it in multiple applications.
With other program for the same purpose it works as expectred, by rolling ball with inertia i can scroll whole page with single move.

**Comment by Seelge** [comment]
Confirmed. When the accumulated moved distance is larger than a threshold, the scroll event is emitted and the distance is reset. If the threshold is surpassed on every mouse event, the maximum speed is reached. There is currently no overflow or measurement by how much the threshold is surpassed.

At ball speeds above that, stuttering seems to appear with only minimal movement at very high ball speeds.
