### ISSUE TITLE
Doesn't work on Windows 10 when some metro apps is open

### ISSUE THREAD

**Issue by Dvornik** [Seelge/TrackballScroll#2]
Great little program.
I hope somebody can fix it. If I open any metro app (settings, for example) and try to scroll anything, application is hanging.

**Comment by Seelge** [comment]
Confirmed. Thanks for narrowing it down to a conflict with metro apps.

**Comment by lukas-buergi** [comment]
It also doesn't work in GTA IV. Which I don't think is a metro app, isn't metro some new windows api or something? And GTA IV is pretty dated.

**Comment by Seelge** [comment]
Yes, metro are those new app from the windows store but also e.g. the Windows 10 configuration menu (Win+i).

I'm not sure why GTA IV does not work, it is possible that it catches the button events itself and thus prevents TrackballScroll from recognizing them.

**Comment by Seelge** [comment]
I cannot reproduce this issue with v2.0.1. Please leave a comment if the application hangs or freezes the mouse cursor again.
