### ISSUE TITLE
wheel reverse scrolling direction

### ISSUE THREAD

**Issue by piggykm** [Seelge/TrackballScroll#20]
Im using trackball on mac / windows(PC)

It is uncomfortable because the wheels are in different directions.
By any chance, can you add options?

Thank you.

**Comment by ArmanHayots** [comment]
Please try this one with added reverse commands in tray.
[TrackballScroll.zip](https://github.com/Seelge/TrackballScroll/files/2131104/TrackballScroll.zip)

**Comment by Seelge** [comment]
Any tests of pull request #22 are appreciated but please note that this version is not reviewed/released yet.

@ArmanHayots 
The link to your version of TrackballScroll.zip seems to point to (this repository)/files/...
but the settings page tells me there are no collaborators configured. Did I somehow allow uploads for other users?

**Comment by ArmanHayots** [comment]
@Seelge I'd just thrown zip into comment and that worked.
I'm not a git nor github user (hg and bitbucket I prefer) and don't even know about such things.

**Comment by piggykm** [comment]
@ArmanHayots 
Thankyou for reply
it works to me!
@Seelge 
Thankyou for assistance
I couldn't find it because I'm not an English speaker.
