### ISSUE TITLE
Can't get it working with Kensington Expert Mouse

### ISSUE THREAD

**Issue by subtleGradient** [Seelge/TrackballScroll#23]
I have the TrackballWorks software running still. Do I need to kill it?

**Comment by ArmanHayots** [comment]
Maybe. For TS working you must ensure that your trackball driver produces standard M4 and M5 clicks. As example, for logitech trackballs this can be overridden in SetPoint software.

**Comment by Seelge** [comment]
Disabling TrackballWorks should serve as a quick test but there is no need to disable it permanently if it allows to revert the button behavior back to the default mouse buttons.

**Comment by Seelge** [comment]
@subtleGradient Did the tips help?

**Comment by Seelge** [comment]
Closed: The question has been answered.
