### ISSUE TITLE
Option to Bind to Middle Mouse

### ISSUE THREAD

**Issue by tomatosoupcan** [Seelge/TrackballScroll#26]
I was wondering if it was possible to add an option to bind to MMB, to completely replace the MMB functionality? Tried binding my MMB to MB4 with X-Mouse control but the Emulate Middle Mouse Click option wasn't working properly that way.

**Comment by Seelge** [comment]
You mean to disable the middle click functionality? That is already available as an option in the menu when right clicking on the tray icon:
![image](https://user-images.githubusercontent.com/2706323/67618650-5fa05480-f7f2-11e9-9192-64c2734d8962.png)

**Comment by piggykm** [comment]
@Seelge I think he wants to change mmb -> mb4

**Comment by tomatosoupcan** [comment]
Yeah, I mean basically add a "Use button MMB" to the list, completely replacing the current MMB functionality.

**Comment by Seelge** [comment]
Thank you for the suggestion but I think it is out of scope of this software with a focus on emulating a scroll wheel.

There are already very good solutions for remapping buttons and keys, I recommend Autohotkey. Remapping the middle mouse button to button 4 (xbutton1) should be as simple as a script containing the line
`MButton::XButton1`

See [Remapping Keys](https://www.autohotkey.com/docs/misc/Remap.htm) and [List of Keys](https://www.autohotkey.com/docs/KeyList.htm).
