### ISSUE TITLE
Modify scrolling rate/distance

### ISSUE THREAD

**Issue by XDTZ** [Seelge/TrackballScroll#27]
If I am using apps thats only recognize step-wise scrolling, it seems the program fires the scrolling event too rapidly. Could you point me the code section or system setting that will make scrolling step fires less? The system scrolling line number setting seems does not matter in this case.
It's an awesome program! Thank you!

**Comment by Seelge** [comment]
Hello @XDTZ ,
thank you for your question. The lines you are searching are in `State.cs`, beginning with line `132`. `X_THRESHOLD` and `Y_THRESHOLD` are the distance in pixels horizontally/vertically before one horizontal/vertical scroll event is emitted.
They are currently at 10 pixels which means for every 10 pixels moved by the trackball, one scroll event is emitted. By increasing these numbers, e.g. to 20, less scroll events will be emitted for the same movement of the trackball.
