### ISSUE TITLE
does not work on visual studio

### ISSUE THREAD

**Issue by marcosbustamantemateo** [Seelge/TrackballScroll#29]

**Comment by Seelge** [comment]
I cannot reproduce the bug description. TrackballScroll works fine with Visual Studio 2019 v16.9.3.

**Comment by marcosbustamantemateo** [comment]
My version of vs is the same and does not scroll in any file... I do not know if I have to configure anything

**Comment by Seelge** [comment]
Does scrolling work for you in any other program, e.g. the file explorer? If not, make sure the trackball buttons emit the the default mouse events.

E.g. for the Logitech Marble Mouse, the settings in the "SetPoint" driver software are set to forward/backward initially, which is not captured by TrackballScroll.

**Comment by marcosbustamantemateo** [comment]
Works on all programs except VS 2019...

**Comment by Seelge** [comment]
This is a wild guess but do you start VS 2019 as administrator? TrackballScroll cannot send signals to software running with different access permissions.
