### ISSUE TITLE
Feature request: Run in background without open terminal window

### ISSUE THREAD

**Issue by lukas-buergi** [Seelge/TrackballScroll#4]
It's a little annoying the window has to stay open all the time.
Maybe there is a way to hide it which should be obvious, but I'm a novice Windows user, sorry.

**Comment by Seelge** [comment]
The application is currently a console application which explains the text-window. A possible solution is to hide the window and add a systray-icon/menu to be able to close the application.

**Comment by Seelge** [comment]
Done with v2.0.0-beta. It seems to work but has not gone through intensive testing and currently uses a default icon.

**Comment by lukas-buergi** [comment]
Thanks again. :-)
Not on Windows right now, will test soon.

About the icon: Maybe try that one? The one named "failed" probably doesn't scale down to small sizes well enough, but the other might do the job. (created by me, use under whatever license you want, say CC0, that public domain thingy)
[icon.zip](https://github.com/Seelge/TrackballScroll/files/253011/icon.zip)

**Comment by Seelge** [comment]
Thanks for the icon but I had a different design in mind, something more colorful (included in v2.0.1). :-)
