### ISSUE TITLE
Cursor jumps around and scroll does not work

### ISSUE THREAD

**Issue by johndevedu** [Seelge/TrackballScroll#5]
First of all, thank you for the software! It works great on my work machine, and does exactly what I want. Problem is with my home setup where I use a laptop with a hi-dpi monitor 3200x1800. I think something about the size scaling (font, apps, etc) feature of Windows 10 appears to throw off the mouse cursor location.

![image](https://cloud.githubusercontent.com/assets/5439943/17668449/1ead986a-62be-11e6-9af1-1c5f9d5208ac.png)

If it's set to 100%, it works fine, but when anything else, it throws the cursor off screen. Any help will be appreciated! If you can point towards where the problem might be, I could also take a crack at it...

Thank you!

**Comment by matrixik** [comment]
I can confirm the same issue on Windows 8.1 with version 2.0.1.

**Comment by Seelge** [comment]
The issue has been fixed by @leohinojosa in #6, I'll create a new version asap.

**Comment by Seelge** [comment]
v2.1.0 is released. Testing with a single monitor went fine but I did encounter some strange behaviour with multiple monitors. I'll  create a new bug for these issues.

**Comment by matrixik** [comment]
I can confirm it's fixed with 2.1.1. Thank you.
